### ISSUE TITLE
Plist.h missing

### ISSUE THREAD

**Issue by cipry0200** [tihmstar/igetnonce#1]
When i try to compile this i get this error: 
![screen shot 2016-12-29 at 13 03 27](https://cloud.githubusercontent.com/assets/23187179/21542632/d7c8bd24-cdc7-11e6-9fee-8c25da816997.png)
How i can fix this?

**Comment by Djsn0wfall** [comment]
Download https://github.com/Chronic-Dev/libplist/blob/master/include/plist/plist.h place it in the project folder and change 
`#include` <plist/plist.h> 
to
`#include` "plist.h"
